<%
distrib, infos    = ENV.fetch('DISTRIB', 'ubuntu:xenial/16.04').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  
verifier:
  name: inspec
  sudo: true
        
provisioner:
  name: salt_solo
  log_level: debug
  omnibus_cachier: true
  salt_install: bootstrap
  salt_version: latest
  salt_minion_id: kitchen-test-spark
  formula: spark
  pillars-from-files:
    spark.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - spark
  state_top:
    base:
      "*":
        - spark
        - spark.debug

platforms:
  - name: ubuntu
    image: "ubuntu/xenial"
    platform: "ubuntu"
    driver_config:
      run_command: /lib/systemd/systemd
      pid_one_command: /lib/systemd/systemd      
      provision_command:
        - apt-get update && apt-get install -y locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8      


suites:
  - name: default
    verifier:
      inspec_tests:
        - name: spark-default
          path: test/integration/default
      controls:
        - spark-baseline
        
  - name: worker
    verifier:
      inspec_tests:
        - name: spark-worker
          path: test/integration/default
      controls:
        - spark-baseline
        - spark-defaults
        - sw-01
        - sw-02
        - sw-03
        - sw-04
    provisioner:
      grains:
        roles:
          - spark-worker

      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.worker
      
  - name: master
    verifier:
      inspec_tests:
        - name: spark-master
          path: test/integration/default
      controls:
        - spark-baseline
        - spark-master-service
        - spark-master-ports
            
    provisioner:
      grains:
        spark:
          lookup:
            master_port: 12345
        roles:
          - spark-master
      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.master
